#!/usr/bin/env python3
"""Idempotent WCAG 2.2 AA-oriented accessibility hardening for /books/."""

import html
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
BOOKS = ROOT / "books"
INDEX = BOOKS / "index.html"

CONCEPT_DOI = "10.5281/zenodo.23046366"
VERSION_DOI = "10.5281/zenodo.23046367"
ZENODO_BADGE = "https://zenodo.org/badge/1305358280.svg"


def improve_cover_alts(text):
    # Static catalog cards generated by seo_books.py.
    def repl(match):
        tag = match.group(0)
        alt_match = re.search(r'alt="([^"]*)"', tag, re.I)
        if not alt_match:
            return tag
        old_alt = html.unescape(alt_match.group(1)).strip()
        title = re.sub(r'\s+book cover$', '', old_alt, flags=re.I).strip()
        if old_alt.lower().startswith("book cover of "):
            title = re.sub(r'^Book cover of\s+', '', old_alt, flags=re.I)
            title = re.sub(r'\s+by Faramarz Kowsari$', '', title, flags=re.I).strip()
        if not title:
            return tag
        new_alt = html.escape(f"Book cover of {title} by Faramarz Kowsari", quote=True)
        return tag[:alt_match.start(1)] + new_alt + tag[alt_match.end(1):]

    return re.sub(r'<img\b[^>]*\bclass="cover"[^>]*>', repl, text, flags=re.I)


def label_cover_links(text):
    # Give the linked cover a functional accessible name distinct from its image description.
    pattern = re.compile(
        r'<a href="(\./[^\"]+/)"(?:\s+aria-label="[^"]*")?><img class="cover"([^>]*)alt="([^"]+)"([^>]*)></a>',
        re.I,
    )

    def repl(match):
        href, before, alt_text, after = match.groups()
        readable = html.unescape(alt_text)
        title = re.sub(r'^Book cover of\s+', '', readable, flags=re.I)
        title = re.sub(r'\s+by Faramarz Kowsari$', '', title, flags=re.I).strip()
        label = html.escape(f"Open the book page for {title}", quote=True)
        return f'<a href="{href}" aria-label="{label}"><img class="cover"{before}alt="{alt_text}"{after}></a>'

    return pattern.sub(repl, text)


def update_index():
    if not INDEX.exists():
        return False
    text = INDEX.read_text(encoding="utf-8")
    original = text

    # Social preview image descriptions.
    if 'property="og:image:alt"' not in text:
        text = text.replace(
            '<meta property="og:image" content="https://github.com/FaramarzKowsari.png">',
            '<meta property="og:image" content="https://github.com/FaramarzKowsari.png"><meta property="og:image:alt" content="Portrait of Faramarz Kowsari, author of the books in this catalog">',
            1,
        )
    if 'name="twitter:image:alt"' not in text:
        text = text.replace(
            '<meta name="twitter:image" content="https://github.com/FaramarzKowsari.png">',
            '<meta name="twitter:image" content="https://github.com/FaramarzKowsari.png"><meta name="twitter:image:alt" content="Portrait of Faramarz Kowsari, author of the books in this catalog">',
            1,
        )

    # Load the small, dedicated DOI component stylesheet without disturbing the main books CSS.
    if 'href="./doi.css"' not in text:
        text = text.replace('</head>', '<link rel="stylesheet" href="./doi.css"></head>', 1)

    # Keyboard bypass and programmatic main target.
    if 'class="skip-link"' not in text:
        text = text.replace('<body>', '<body><a class="skip-link" href="#main-content">Skip to book catalog</a>', 1)
    text = text.replace('<main class="wrap">', '<main class="wrap" id="main-content" tabindex="-1">', 1)

    # Keep the two important internal discovery links prominent at the top of /books/.
    # This is applied after seo_books.py, so future catalog rebuilds retain the navigation.
    hero_actions = (
        '<div class="actions">'
        '<a class="action primary" href="./topics/" aria-label="Browse Faramarz Kowsari books by topic">Browse books by topic</a>'
        '<a class="action" href="./author/" aria-label="Read the author profile of Faramarz Kowsari">About the author</a>'
        '<a class="action" href="https://play.google.com/store/search?q=Faramarz%20Kowsari&c=books" target="_blank" rel="noopener noreferrer">Find Faramarz Kowsari on Google Books</a>'
        '</div>'
    )
    text = re.sub(
        r'<div class="actions">.*?</div>(?=</header>)',
        hero_actions,
        text,
        count=1,
        flags=re.S,
    )

    # Persistent Zenodo citation panel. The concept DOI represents all versions;
    # the version DOI identifies the archived v1.0.0 release exactly.
    text = re.sub(
        r'<!-- zenodo-doi:start -->.*?<!-- zenodo-doi:end -->',
        '',
        text,
        flags=re.S,
    )
    doi_panel = (
        '<!-- zenodo-doi:start -->'
        '<aside class="zenodo-doi-card" aria-label="Zenodo DOI and citation information">'
        '<a class="zenodo-doi-badge" href="https://doi.org/' + CONCEPT_DOI + '" target="_blank" rel="noopener noreferrer" '
        'aria-label="Open the Zenodo record for all versions of the Faramarz Kowsari website and books library">'
        '<img src="' + ZENODO_BADGE + '" alt="Zenodo DOI badge for the Faramarz Kowsari official website and books library" loading="lazy" decoding="async">'
        '</a>'
        '<div class="zenodo-doi-copy">'
        '<strong>Citable archive on Zenodo</strong>'
        '<p>Persistent DOI for all versions: <a href="https://doi.org/' + CONCEPT_DOI + '" target="_blank" rel="noopener noreferrer">' + CONCEPT_DOI + '</a>'
        '<span aria-hidden="true"> · </span><span class="doi-version">v1.0.0 DOI: <a href="https://doi.org/' + VERSION_DOI + '" target="_blank" rel="noopener noreferrer">' + VERSION_DOI + '</a></span></p>'
        '</div>'
        '</aside>'
        '<!-- zenodo-doi:end -->'
    )
    text = text.replace('</header>', doi_panel + '</header>', 1)

    # Named catalog section and an explicit form label for search.
    text = re.sub(
        r'<section><h2>(?:Source-reviewed book pages|Explore the book collection|Book catalog)</h2>',
        '<section aria-labelledby="book-catalog-title"><h2 id="book-catalog-title">Explore the book collection</h2>',
        text,
        count=1,
    )
    text = re.sub(
        r'<p id="completed-count" class="count">',
        '<p id="completed-count" class="count" role="status" aria-live="polite" aria-atomic="true">',
        text,
        count=1,
    )
    text = re.sub(
        r'<div class="toolbar"><input id="q" type="search" placeholder="Search by title, language or category\.\.\." aria-label="Search books"></div>',
        '<div class="toolbar"><label class="sr-only" for="q">Search books by title, language or category</label><input id="q" type="search" placeholder="Search by title, language or category..." aria-describedby="completed-count" autocomplete="off"></div>',
        text,
        count=1,
    )
    text = text.replace(
        '<div id="completed-grid" class="grid">',
        '<div id="completed-grid" class="grid" aria-label="Book results">',
        1,
    )

    text = improve_cover_alts(text)
    text = label_cover_links(text)

    # Use the card heading to give each repeated button a unique accessible name.
    card_pattern = re.compile(r'(<article class="card".*?</article>)', re.S)
    def card_repl(match):
        block = match.group(1)
        h = re.search(r'<h2><a href="[^"]+">(.*?)</a></h2>', block, re.S)
        b = re.search(r'<a class="btn" href="([^"]+)"(?: aria-label="[^"]*")?>View book</a>', block)
        if not h or not b:
            return block
        title = re.sub(r'<[^>]+>', ' ', h.group(1))
        title = html.unescape(re.sub(r'\s+', ' ', title)).strip()
        label = html.escape(f"View book: {title}", quote=True)
        return block[:b.start()] + f'<a class="btn" href="{b.group(1)}" aria-label="{label}">View book</a>' + block[b.end():]
    text = card_pattern.sub(card_repl, text)

    if text != original:
        INDEX.write_text(text, encoding="utf-8")
        return True
    return False


def main():
    changed = update_index()
    print("WCAG books catalog hardening: " + ("updated" if changed else "no changes needed"))


if __name__ == "__main__":
    main()
